import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1000,
  tileGap: 400,
  mobileMaxCircles: 2,
  mobileScale: 0.55,
  circles: [
    {
      id: 'hist-c1',
      xPercent: 10,
      yPercent: 10,
      ellipses: [
        {
          id: 'he1a',
          layer: 0,
          zIndex: 0,
          width: 520,
          height: 520,
          offsetX: 0,
          offsetY: 0,
          rotation: -10,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'he1b',
          layer: 2,
          zIndex: 1,
          width: 520,
          height: 520,
          offsetX: 10,
          offsetY: 10,
          rotation: -90,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'he1c',
          layer: 1,
          zIndex: 2,
          width: 520,
          height: 520,
          offsetX: 5,
          offsetY: 5,
          rotation: -10,
          borderRadius: '50%',
          borderWidth: 40,
        },
      ],
    },
    {
      id: 'hist-c2',
      xPercent: 90,
      yPercent: 90,
      ellipses: [
        {
          id: 'he2a',
          layer: 0,
          zIndex: 0,
          width: 520,
          height: 520,
          offsetX: 0,
          offsetY: 0,
          rotation: 170,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'he2b',
          layer: 2,
          zIndex: 1,
          width: 520,
          height: 520,
          offsetX: -10,
          offsetY: -10,
          rotation: 90,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'he2c',
          layer: 1,
          zIndex: 2,
          width: 520,
          height: 520,
          offsetX: -5,
          offsetY: -5,
          rotation: 170,
          borderRadius: '50%',
          borderWidth: 40,
        },
      ],
    },
  ],
  images: [
    {
      id: 'hist-paper1',
      src: 'paper.svg',
      xPercent: 50,
      yPercent: 5,
      width: 170,
      height: 250,
      rotation: 0,
      opacity: 1,
    },
    {
      id: 'hist-paper2',
      src: 'paper.svg',
      xPercent: 50,
      yPercent: 95,
      width: 170,
      height: 250,
      rotation: 180,
      opacity: 1,
    },
  ],
};
