import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1100,
  tileGap: 350,
  mobileMaxCircles: 2,
  mobileScale: 0.5,
  circles: [
    {
      id: 'c1',
      xPercent: 110,
      yPercent: 30,
      ellipses: [
        {
          id: 'e1a',
          layer: 0,
          zIndex: 0,
          width: 600,
          height: 600,
          offsetX: 0,
          offsetY: 0,
          rotation: -60,
          borderRadius: '50%',
          borderWidth: 48,
        },
        {
          id: 'e1b',
          layer: 2,
          zIndex: 1,
          width: 600,
          height: 600,
          offsetX: 30,
          offsetY: 10,
          rotation: -120,
          borderRadius: '50%',
          borderWidth: 48,
        },
        {
          id: 'e1c',
          layer: 1,
          zIndex: 2,
          width: 600,
          height: 600,
          offsetX: 15,
          offsetY: 5,
          rotation: -60,
          borderRadius: '50%',
          borderWidth: 48,
        },
      ],
    },
    {
      id: 'c2',
      xPercent: -5,
      yPercent: 10,
      ellipses: [
        {
          id: 'e2a',
          layer: 0,
          zIndex: 0,
          width: 500,
          height: 480,
          offsetX: 0,
          offsetY: 50,
          rotation: -15,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'e2b',
          layer: 2,
          zIndex: 1,
          width: 500,
          height: 480,
          offsetX: 10,
          offsetY: 40,
          rotation: -45,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'e2c',
          layer: 1,
          zIndex: 2,
          width: 500,
          height: 480,
          offsetX: 5,
          offsetY: 30,
          rotation: -15,
          borderRadius: '50%',
          borderWidth: 40,
        },
      ],
    },
  ],
  images: [
    {
      id: 'paper1',
      src: 'paper.svg',
      xPercent: 40,
      yPercent: 5,
      width: 170,
      height: 250,
      rotation: 5,
      opacity: 0.85,
    },
    {
      id: 'paper2',
      src: 'paper.svg',
      xPercent: 60,
      yPercent: 85,
      width: 170,
      height: 250,
      rotation: -30,
      opacity: 0.85,
    },
  ],
};
