import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1050,
  tileGap: 450,
  mobileMaxCircles: 2,
  mobileScale: 0.58,
  circles: [
    {
      id: 'c1',
      xPercent: -5,
      yPercent: 85,
      ellipses: [
        {
          id: 'e1a',
          layer: 0,
          zIndex: 0,
          width: 580,
          height: 580,
          offsetX: 0,
          offsetY: 0,
          rotation: 75,
          borderRadius: '50%',
          borderWidth: 46,
        },
        {
          id: 'e1b',
          layer: 2,
          zIndex: 1,
          width: 580,
          height: 580,
          offsetX: -20,
          offsetY: 10,
          rotation: 15,
          borderRadius: '50%',
          borderWidth: 46,
        },
        {
          id: 'e1c',
          layer: 1,
          zIndex: 2,
          width: 580,
          height: 580,
          offsetX: -10,
          offsetY: 5,
          rotation: 75,
          borderRadius: '50%',
          borderWidth: 46,
        },
      ],
    },
    {
      id: 'c2',
      xPercent: 105,
      yPercent: 15,
      ellipses: [
        {
          id: 'e2a',
          layer: 0,
          zIndex: 0,
          width: 620,
          height: 620,
          offsetX: 0,
          offsetY: 0,
          rotation: -10,
          borderRadius: '50%',
          borderWidth: 50,
        },
        {
          id: 'e2b',
          layer: 2,
          zIndex: 1,
          width: 620,
          height: 620,
          offsetX: 15,
          offsetY: -10,
          rotation: -70,
          borderRadius: '50%',
          borderWidth: 50,
        },
        {
          id: 'e2c',
          layer: 1,
          zIndex: 2,
          width: 620,
          height: 620,
          offsetX: 8,
          offsetY: -5,
          rotation: -10,
          borderRadius: '50%',
          borderWidth: 50,
        },
      ],
    },
  ],
  images: [
    {
      id: 'paper1',
      src: 'paper.svg',
      xPercent: 75,
      yPercent: 40,
      width: 200,
      height: 300,
      rotation: 40,
      opacity: 0.7,
    },
    {
      id: 'paper2',
      src: 'paper.svg',
      xPercent: 20,
      yPercent: 10,
      width: 200,
      height: 300,
      rotation: -5,
      opacity: 0.7,
    },
  ],
};
