import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1400,
  tileGap: 200,
  mobileMaxCircles: 2,
  mobileScale: 0.7,
  circles: [
    {
      id: 'c1',
      xPercent: 0,
      yPercent: 0,
      ellipses: [
        {
          id: 'e1a',
          layer: 0,
          zIndex: 0,
          width: 800,
          height: 800,
          offsetX: 0,
          offsetY: 0,
          rotation: -45,
          borderRadius: '50%',
          borderWidth: 60,
        },
        {
          id: 'e1b',
          layer: 2,
          zIndex: 1,
          width: 800,
          height: 800,
          offsetX: 20,
          offsetY: 20,
          rotation: -135,
          borderRadius: '50%',
          borderWidth: 60,
        },
        {
          id: 'e1c',
          layer: 1,
          zIndex: 2,
          width: 800,
          height: 800,
          offsetX: 10,
          offsetY: 10,
          rotation: -45,
          borderRadius: '50%',
          borderWidth: 60,
        },
      ],
    },
    {
      id: 'c2',
      xPercent: 100,
      yPercent: 100,
      ellipses: [
        {
          id: 'e2a',
          layer: 0,
          zIndex: 0,
          width: 800,
          height: 800,
          offsetX: 0,
          offsetY: 0,
          rotation: 45,
          borderRadius: '50%',
          borderWidth: 60,
        },
        {
          id: 'e2b',
          layer: 2,
          zIndex: 1,
          width: 800,
          height: 800,
          offsetX: -20,
          offsetY: -20,
          rotation: 135,
          borderRadius: '50%',
          borderWidth: 60,
        },
        {
          id: 'e2c',
          layer: 1,
          zIndex: 2,
          width: 800,
          height: 800,
          offsetX: -10,
          offsetY: -10,
          rotation: 45,
          borderRadius: '50%',
          borderWidth: 60,
        },
      ],
    },
  ],
  images: [
    {
      id: 'paper1',
      src: 'paper.svg',
      xPercent: 10,
      yPercent: 90,
      width: 250,
      height: 370,
      rotation: -15,
      opacity: 0.6,
    },
    {
      id: 'paper2',
      src: 'paper.svg',
      xPercent: 90,
      yPercent: 10,
      width: 250,
      height: 370,
      rotation: 15,
      opacity: 0.6,
    },
  ],
};
