import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1100,
  tileGap: 450,
  mobileMaxCircles: 2,
  mobileScale: 0.55,
  circles: [
    {
      id: 'c1',
      xPercent: -15,
      yPercent: 20,
      ellipses: [
        {
          id: 'e1a',
          layer: 0,
          zIndex: 0,
          width: 500,
          height: 500,
          offsetX: 0,
          offsetY: 0,
          rotation: -15,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'e1b',
          layer: 2,
          zIndex: 1,
          width: 500,
          height: 500,
          offsetX: 10,
          offsetY: -5,
          rotation: -75,
          borderRadius: '50%',
          borderWidth: 40,
        },
        {
          id: 'e1c',
          layer: 1,
          zIndex: 2,
          width: 500,
          height: 500,
          offsetX: 5,
          offsetY: 0,
          rotation: -15,
          borderRadius: '50%',
          borderWidth: 40,
        },
      ],
    },
    {
      id: 'c2',
      xPercent: 95,
      yPercent: 60,
      ellipses: [
        {
          id: 'e2a',
          layer: 0,
          zIndex: 0,
          width: 650,
          height: 600,
          offsetX: 0,
          offsetY: 0,
          rotation: 30,
          borderRadius: '50%',
          borderWidth: 52,
        },
        {
          id: 'e2b',
          layer: 2,
          zIndex: 1,
          width: 650,
          height: 600,
          offsetX: -15,
          offsetY: 10,
          rotation: 60,
          borderRadius: '50%',
          borderWidth: 52,
        },
        {
          id: 'e2c',
          layer: 1,
          zIndex: 2,
          width: 650,
          height: 600,
          offsetX: -10,
          offsetY: 5,
          rotation: 30,
          borderRadius: '50%',
          borderWidth: 52,
        },
      ],
    },
  ],
  images: [
    {
      id: 'paper1',
      src: 'paper.svg',
      xPercent: 80,
      yPercent: 5,
      width: 180,
      height: 270,
      rotation: 22,
      opacity: 0.8,
    },
    {
      id: 'paper2',
      src: 'paper.svg',
      xPercent: 15,
      yPercent: 80,
      width: 180,
      height: 270,
      rotation: -8,
      opacity: 0.8,
    },
  ],
};
