import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1200,
  tileGap: 400,
  mobileMaxCircles: 2,
  mobileScale: 0.6,
  circles: [
    {
      id: 'prof-c1',
      xPercent: -20,
      yPercent: 0,
      ellipses: [
        {
          id: 'pe1a',
          layer: 0,
          zIndex: 0,
          width: 600,
          height: 600,
          offsetX: 0,
          offsetY: 0,
          rotation: 45,
          borderRadius: '50%',
          borderWidth: 48,
        },
        {
          id: 'pe1b',
          layer: 2,
          zIndex: 1,
          width: 600,
          height: 600,
          offsetX: -15,
          offsetY: 15,
          rotation: 90,
          borderRadius: '50%',
          borderWidth: 48,
        },
        {
          id: 'pe1c',
          layer: 1,
          zIndex: 2,
          width: 600,
          height: 600,
          offsetX: -8,
          offsetY: 8,
          rotation: 45,
          borderRadius: '50%',
          borderWidth: 48,
        },
      ],
    },
    {
      id: 'prof-c2',
      xPercent: 120,
      yPercent: 80,
      ellipses: [
        {
          id: 'pe2a',
          layer: 0,
          zIndex: 0,
          width: 700,
          height: 700,
          offsetX: 0,
          offsetY: 0,
          rotation: -30,
          borderRadius: '50%',
          borderWidth: 55,
        },
        {
          id: 'pe2b',
          layer: 2,
          zIndex: 1,
          width: 700,
          height: 700,
          offsetX: 20,
          offsetY: -10,
          rotation: -60,
          borderRadius: '50%',
          borderWidth: 55,
        },
        {
          id: 'pe2c',
          layer: 1,
          zIndex: 2,
          width: 700,
          height: 700,
          offsetX: 10,
          offsetY: -5,
          rotation: -30,
          borderRadius: '50%',
          borderWidth: 55,
        },
      ],
    },
  ],
  images: [
    {
      id: 'prof-paper1',
      src: 'paper.svg',
      xPercent: 90,
      yPercent: 10,
      width: 210,
      height: 310,
      rotation: -12,
      opacity: 0.8,
    },
    {
      id: 'prof-paper2',
      src: 'paper.svg',
      xPercent: 10,
      yPercent: 90,
      width: 210,
      height: 310,
      rotation: 18,
      opacity: 0.8,
    },
  ],
};
