import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1150,
  tileGap: 380,
  mobileMaxCircles: 2,
  mobileScale: 0.52,
  circles: [
    {
      id: 'c1',
      xPercent: -10,
      yPercent: 0,
      ellipses: [
        {
          id: 'e1a',
          layer: 0,
          zIndex: 0,
          width: 540,
          height: 540,
          offsetX: 0,
          offsetY: 0,
          rotation: -15,
          borderRadius: '50%',
          borderWidth: 42,
        },
        {
          id: 'e1b',
          layer: 2,
          zIndex: 1,
          width: 540,
          height: 540,
          offsetX: 10,
          offsetY: 20,
          rotation: -45,
          borderRadius: '50%',
          borderWidth: 42,
        },
        {
          id: 'e1c',
          layer: 1,
          zIndex: 2,
          width: 540,
          height: 540,
          offsetX: 5,
          offsetY: 10,
          rotation: -15,
          borderRadius: '50%',
          borderWidth: 42,
        },
      ],
    },
    {
      id: 'c2',
      xPercent: 100,
      yPercent: 80,
      ellipses: [
        {
          id: 'e2a',
          layer: 0,
          zIndex: 0,
          width: 680,
          height: 640,
          offsetX: 0,
          offsetY: 0,
          rotation: 20,
          borderRadius: '50%',
          borderWidth: 54,
        },
        {
          id: 'e2b',
          layer: 2,
          zIndex: 1,
          width: 680,
          height: 640,
          offsetX: -20,
          offsetY: -10,
          rotation: 80,
          borderRadius: '50%',
          borderWidth: 54,
        },
        {
          id: 'e2c',
          layer: 1,
          zIndex: 2,
          width: 680,
          height: 640,
          offsetX: -10,
          offsetY: -5,
          rotation: 20,
          borderRadius: '50%',
          borderWidth: 54,
        },
      ],
    },
  ],
  images: [
    {
      id: 'paper1',
      src: 'paper.svg',
      xPercent: 90,
      yPercent: 20,
      width: 185,
      height: 280,
      rotation: -10,
      opacity: 1,
    },
    {
      id: 'paper2',
      src: 'paper.svg',
      xPercent: 10,
      yPercent: 60,
      width: 185,
      height: 280,
      rotation: 25,
      opacity: 1,
    },
  ],
};
