import type { BGConfig } from '@shared/model';

/**
 * Background configuration for the Home Page.
 */
export const BG_LAYOUT_CONFIG: BGConfig = {
  tileHeight: 1300,
  tileGap: 250,
  mobileMaxCircles: 2,
  mobileScale: 0.65,
  circles: [
    {
      id: 'c1',
      xPercent: 50,
      yPercent: -10,
      ellipses: [
        {
          id: 'e1a',
          layer: 0,
          zIndex: 0,
          width: 700,
          height: 700,
          offsetX: 0,
          offsetY: 0,
          rotation: 0,
          borderRadius: '50%',
          borderWidth: 55,
        },
        {
          id: 'e1b',
          layer: 2,
          zIndex: 1,
          width: 700,
          height: 700,
          offsetX: 0,
          offsetY: 20,
          rotation: 90,
          borderRadius: '50%',
          borderWidth: 55,
        },
        {
          id: 'e1c',
          layer: 1,
          zIndex: 2,
          width: 700,
          height: 700,
          offsetX: 0,
          offsetY: 10,
          rotation: 0,
          borderRadius: '50%',
          borderWidth: 55,
        },
      ],
    },
    {
      id: 'c2',
      xPercent: 10,
      yPercent: 70,
      ellipses: [
        {
          id: 'e2a',
          layer: 0,
          zIndex: 0,
          width: 550,
          height: 520,
          offsetX: 0,
          offsetY: 0,
          rotation: -30,
          borderRadius: '50%',
          borderWidth: 44,
        },
        {
          id: 'e2b',
          layer: 2,
          zIndex: 1,
          width: 550,
          height: 520,
          offsetX: 15,
          offsetY: -5,
          rotation: -60,
          borderRadius: '50%',
          borderWidth: 44,
        },
        {
          id: 'e2c',
          layer: 1,
          zIndex: 2,
          width: 550,
          height: 520,
          offsetX: 8,
          offsetY: -2,
          rotation: -30,
          borderRadius: '50%',
          borderWidth: 44,
        },
      ],
    },
  ],
  images: [
    {
      id: 'paper1',
      src: 'paper.svg',
      xPercent: 85,
      yPercent: 15,
      width: 220,
      height: 330,
      rotation: 12,
      opacity: 0.95,
    },
    {
      id: 'paper2',
      src: 'paper.svg',
      xPercent: 5,
      yPercent: 85,
      width: 220,
      height: 330,
      rotation: -18,
      opacity: 0.95,
    },
  ],
};
